version: '3.0'
services:
  localstack:
    image: localstack/localstack:latest
    environment: 
      - SERVICES=sqs,s3
    ports:
      - "4565-4599:4565-4599"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"